"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup, Command
import os

class clean(Command):
    user_options = []
    def initialize_options(self):
        pass 
    def finalize_options(self):
        pass
    def run(self):
        os.system("rm -rf build dist *.pyc")

APP = ['SnapPython.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True, 'semi_standalone': True,
           'excludes': 'scipy,numpy,OpenGL',
           'packages': 'SnapPy',
           'includes': 'IPython.Extensions.ipy_profile_none',
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    cmdclass   = {'clean' : clean},
)
