"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['SnapPython.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True,
 'excludes': 'scipy,numpy',
 'packages': 'SnapPy',
 'includes': 'IPython.Extensions.ipy_profile_none,gzip,tarfile'
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
