cirrus_wheels_macos_arm64_task:
  name: Build macOS arm64 wheels.
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:latest
  env:
    CIBW_ARCHS_MACOS: arm64
    CIBW_SKIP: pp* cp38* cp312*
    CIBW_BEFORE_BUILD: >
      pip install cython FXrays low_index sphinx sphinx_rtd_theme &&
      pip install --pre --extra-index-url https://test.pypi.org/simple cypari &&
      pip install git+https://github.com/3-manifolds/PLink &&
      pip install git+https://github.com/3-manifolds/snappy_manifolds &&
      pip install git+https://github.com/3-manifolds/Spherogram
    CIBW_BEFORE_TEST: >
      pip install cython low_index &&
      pip install --pre --extra-index-url https://test.pypi.org/simple cypari &&
      pip install git+https://github.com/3-manifolds/PLink &&
      pip install git+https://github.com/3-manifolds/snappy_manifolds &&
      pip install git+https://github.com/3-manifolds/Spherogram
    CIBW_TEST_COMMAND: python -m snappy.test --skip-modern-opengl
  install_pre_requirements_script:
    - brew install python3 pipx
    - python3 --version
  run_cibuildwheel_script:
    - pipx run cibuildwheel --output-dir wheelhouse
  wheels_artifacts:
    path: "wheelhouse/*"
