# We test both Sage 8.9 (the last version to use Python 2.7) and 9.0
# (which uses Python 3.0).

language: python

services:
  - docker

before_install:
  - docker pull sagemath/sagemath:9.1
  - docker pull sagemath/sagemath:develop

script:
  - docker run -v `pwd`:/snappy sagemath/sagemath:9.1 bash /snappy/dev/build_and_test_in_sage.bash
  - docker run -v `pwd`:/snappy sagemath/sagemath:develop bash /snappy/dev/build_and_test_in_sage.bash
