language: python

services:
  - docker

before_install:
  - docker pull sagemath/sagemath:8.8
  - docker pull computop/sage:py3

script:
  - docker run -v `pwd`:/snappy sagemath/sagemath:8.8 bash /snappy/dev/build_and_test_in_sage.bash
  - docker run -v `pwd`:/snappy computop/sage:py3 bash /snappy/dev/build_and_test_in_sage.bash
