from ..cache import SnapPyCache

cdef class OrbTriangulation:
    """

    >>> o = Orb.OrbifoldTriangulation("ORB_FILE.orb") # doctest: +SKIP
     # Recreates triangulation from diagram, forgets what user entered for singular locus
    >>> o.retriangulate() # doctest: +SKIP

    """

    cdef c_Triangulation* c_triangulation
    cdef c_Diagram* c_diagram
    cdef readonly _cache

    def __cinit__(self, spec=None, remove_finite_vertices=True):
        self.c_triangulation = NULL
        self.c_diagram = NULL
        self._cache = SnapPyCache()

        for attr in [
                '_to_orb_string',
                '_to_snappea_string',
                '__snappy__',
                'snapPea',
                '_to_string']:
            if hasattr(spec, attr):
                spec = getattr(spec, attr)()
                break

        if spec is None:
            self.get_from_new_plink()
        elif spec == 'empty':
            pass
        else:
            if not isinstance(spec, (str, bytes)):
                raise TypeError("Expected str or bytes (TODO: fill in error")
            self.get_triangulation(
                spec, remove_finite_vertices=remove_finite_vertices)

            if self.c_triangulation == NULL:
                raise RuntimeError('An empty triangulation was generated.')

    def __dealloc__(self):
        if self.c_triangulation != NULL:
            free_triangulation(self.c_triangulation)
        if self.c_diagram != NULL:
            free_diagram(self.c_diagram)

    cdef get_from_new_plink(self, file_name=None):
        raise NotImplementedError("Orbifold PLink not implemented yet.")

    cdef get_triangulation(self, spec, remove_finite_vertices=True):
        if ( isinstance(spec, str) and spec.startswith('% Triangulation') or
             isinstance(spec, bytes) and spec.startswith(b'% Triangulation')):
            self._from_triangulation_string(
                spec, remove_finite_vertices=remove_finite_vertices)
            return
        if (isinstance(spec, str) and spec.startswith('% orb') or
            isinstance(spec, bytes) and spec.startswith(b'% orb')):
            self._from_orb_string(
                spec, remove_finite_vertices=remove_finite_vertices)

        self.get_from_file(spec, remove_finite_vertices)

    def _from_triangulation_string(self, string, remove_finite_vertices=True):
        """
        WARNING: Users should not use this function directly.  To
        create a Triangulation or Manifold or ManifoldHP from a string
        containing the contents of a triangulation file, simply do:

        >>> M = Manifold('7_4')
        >>> seed = M._to_string()
        >>> N = Manifold(seed)
        >>> N == M
        True

        Fill an empty Triangulation from a string generated by
        _to_string.
        """
        if self.c_triangulation is not NULL:
            raise ValueError('The Triangulation must be empty.')
        self.c_triangulation = read_triangulation_from_string(
            to_bytes(string))
        if remove_finite_vertices:
            self._remove_finite_vertices()

    def _from_orb_string(self, string, remove_finite_vertices=True):
        if self.c_triangulation is not NULL:
            raise ValueError('The Triangulation must be empty.')
        if self.c_diagram is not NULL:
            raise ValueError('The diagram must be empty.')
        read_orb_from_string(
            to_bytes(string), &self.c_triangulation, &self.c_diagram)
        if remove_finite_vertices:
            self._remove_finite_vertices()

    def get_from_file(self, name, remove_finite_vertices=True):
        locations = [os.curdir]
        env_var_name = 'SNAPPEA_MANIFOLD_DIRECTORY'
        location = os.environ.get(env_var_name)
        if location is not None:
            locations.append(location)
        for location in locations:
            path = os.path.join(location, name)
            if os.path.isfile(path):
                with open(path) as file:
                    first_line = file.readline()
                if first_line.startswith('% orb'):
                    read_orb(
                        to_bytes(path),
                        &self.c_triangulation, &self.c_diagram)
                elif first_line.startswith('% Triangulation'):
                    self.c_triangulation = read_triangulation(to_bytes(path))
                else:
                    raise IOError('File %s has unknown file format.' % name)
                break
        if self.c_triangulation == NULL:
            raise IOError(
                'The orbifold or manifold file %s was not found.' % name)
        if remove_finite_vertices:
            self._remove_finite_vertices()
            
    def _remove_finite_vertices(self):
        if self.c_triangulation == NULL:
            return
        remove_finite_vertices(self.c_triangulation)

    def _to_orb_string(self) -> str:
        cdef char *c_string
        cdef result
        if self.c_triangulation is NULL:
            raise ValueError('The Triangulation is empty.')

        try:
            c_string = write_orb_to_string(self.c_triangulation, self.c_diagram)
            result : bytes = c_string
        finally:
            free(c_string)
        return result.decode()

    def _to_snappea_string(self):
        cdef char *c_string
        cdef result
        if self.c_triangulation is NULL:
            raise ValueError('The Triangulation is empty.')

        try:
            c_string = string_triangulation(self.c_triangulation)
            result : bytes = c_string
        finally:
            free(c_string)
        return result.decode()

    def retriangulate_diagram(self):
        """
        Demo
        """

        if self.c_diagram == NULL:
            return False

        # TODO: fix memory leak

        self.c_triangulation = triangulate_diagram_complement(
            self.c_diagram, True)

        return True

    def fundamental_group(
            self,
            simplify_presentation : bool = True,
            fillings_may_affect_generators : bool = True,
            minimize_number_of_generators : bool = True,
            try_hard_to_shorten_relators : bool = True
            ) -> FundamentalGroup:
        if self.c_triangulation is NULL:
            raise ValueError('The Triangulation is empty.')
        args = (simplify_presentation, fillings_may_affect_generators,
                minimize_number_of_generators, try_hard_to_shorten_relators)
        try:
            return self._cache.lookup('fundamental_group', *args)
        except KeyError:
            pass

        return self._cache.save(FundamentalGroup(self, *args),
                                'fundamental_group', *args)

    def num_cusps(self, cusp_type='all') -> int:
        """
        Return the total number of cusps.  By giving the optional argument
        'orientable' or 'nonorientable' it will only count cusps of that type.

        >>> M = Triangulation('m125')
        >>> M.num_cusps()
        2
        """
        if cusp_type == 'all':
            return get_num_cusps(self.c_triangulation)
        elif cusp_type == 'orientable':
            return get_num_or_cusps(self.c_triangulation)
        elif cusp_type == 'nonorientable':
            return get_num_nonor_cusps(self.c_triangulation)
        else:
            raise ValueError("Acceptable cusp types are "
                             "['all', 'orientable', 'nonorientable'].")
