name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          # Skip Python 2.7 and 3.5, 32 bit Linux, and PyPy
          CIBW_SKIP: cp27-* cp35-* cp36-* cp37-* cp39-* *-manylinux_i686 pp*
          CIBW_BEFORE_BUILD_WINDOWS: |
            pip install cython sphinx || 
            pip install https://github.com/3-manifolds/PLink/archive/master.zip ||
            pip install https://github.com/3-manifolds/snappy_manifolds/archive/master.zip ||
            pip install https://github.com/3-manifolds/Spherogram/archive/master.zip
          CIBW_BEFORE_TEST: |
            pip install cython sphinx https://github.com/3-manifolds/PLink/archive/master.zip https://github.com/3-manifolds/snappy_manifolds/archive/master.zip https://github.com/3-manifolds/Spherogram/archive/master.zip
          CIBW_TEST_COMMAND: python -m snappy.test --skip-modern-opengl

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
