name: Linux Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.8'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          # Skip Python 2.7, 3.5, 3.11, 32 bit Linux, and PyPy
          CIBW_SKIP: cp27-* cp35-* *-manylinux_i686 *musllinux* pp*
          CIBW_BEFORE_ALL_LINUX: yum install -y tk mesa-libGLU-devel
          CIBW_BEFORE_BUILD: >
            pip install cython FXrays sphinx sphinx_rtd_theme &&
            pip install --pre --extra-index-url https://test.pypi.org/simple cypari &&
            pip install git+https://github.com/3-manifolds/PLink &&
            pip install git+https://github.com/3-manifolds/snappy_manifolds &&
            pip install git+https://github.com/3-manifolds/Spherogram &&
            pip install git+https://github.com/3-manifolds/low_index
          CIBW_BEFORE_TEST: >
            pip install cython &&
            pip install --pre --extra-index-url https://test.pypi.org/simple cypari &&
            pip install git+https://github.com/3-manifolds/PLink &&
            pip install git+https://github.com/3-manifolds/snappy_manifolds &&
            pip install git+https://github.com/3-manifolds/Spherogram &&
            pip install git+https://github.com/3-manifolds/low_index
          CIBW_REPAIR_WHEEL_COMMAND_LINUX: auditwheel repair --strip -w {dest_dir} {wheel}
          CIBW_TEST_COMMAND: python -m snappy.test --skip-modern-opengl

      - uses: actions/upload-artifact@v3
        with:
          name: snappy_linux_wheels
          path: ./wheelhouse/*.whl
