name: macOS Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, macos-13]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        name: Install Python
        with:
          python-version: '3.9'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel

      - name: Build wheels
        run: |
          python -m "cibuildwheel==2.12.3" --output-dir wheelhouse
        env:
          # Skip Python 2.7, 3.5, 3.11, 32 bit Linux, and PyPy
          CIBW_BUILD: "cp310-*"
          CIBW_ARCHS_MACOS: x86_64
          CIBW_BEFORE_BUILD: >
            pip install "cython<3.0" FXrays low_index sphinx sphinx_rtd_theme &&
            pip install --pre --extra-index-url https://test.pypi.org/simple cypari &&
            pip install git+https://github.com/3-manifolds/PLink &&
            pip install git+https://github.com/3-manifolds/snappy_manifolds &&
            pip install git+https://github.com/3-manifolds/Spherogram
          CIBW_BEFORE_TEST: >
            pip install "cython<3.0" low_index &&
            pip install --pre --extra-index-url https://test.pypi.org/simple cypari &&
            pip install git+https://github.com/3-manifolds/PLink &&
            pip install git+https://github.com/3-manifolds/snappy_manifolds &&
            pip install git+https://github.com/3-manifolds/Spherogram
          CIBW_TEST_COMMAND: python -m snappy.test --skip-modern-opengl

      - uses: actions/upload-artifact@v3
        with:
          name: snappy_macos_wheels
          path: ./wheelhouse/*.whl
