name: sage-test

on: [push, pull_request]


jobs:
  test:
    name: Test on Sage
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        version: [9.1, develop]

    container:
      image: sagemath/sagemath:${{ matrix.version }}

    steps:
      - name: Sage version
        run: sage --version

      - name: Go home
        # https://github.com/actions/runner/issues/863
        run: sudo chown sage:sage $HOME           

      - name: Install PLink
        run: 
          sage -pip install -U https://github.com/3-manifolds/PLink/archive/master.zip

      - name: Install snappy_manifolds
        run: sage -pip install -U https://github.com/3-manifolds/snappy_manifolds/archive/master.zip

      - name: Install spherogram
        run: sage -pip install -U https://github.com/3-manifolds/spherogram/archive/master.zip

      - name: Test spherogram
        run: sage -python -m spherogram.test 

      - name: Install snappy
        run: sage -pip install -U https://github.com/3-manifolds/snappy/archive/master.zip

      - name: Do the tests
        run: sage -python -m snappy.test
