name: sage-test

on: [push, pull_request]

runs-on: ubuntu-latest

jobs:
  test:
    name: Test on Sage
    container:
      image: alpine:latest

    steps:
      - name: try
        run: cat /etc/alpine-release

      - name: again
        run: cat python/version.py
