name: sage-test

on: [push, pull_request]


jobs:
  test:
    name: Test on Sage
    runs-on: ubuntu-latest 

    container:
      image: alpine:latest

      steps:
        - name: try
          run: cat /etc/alpine-release

          - name: again
            run: cat python/version.py
