name: sage-test

on: [push, pull_request]


jobs:
  test:
    name: Test on Sage
    runs-on: ubuntu-latest 

    container:
      image: sagemath/sagemath:9.1

    steps:
      - uses: actions/checkout@v2
        
      - name: Sage version
        run: sage --version

      - name: Install PLink
        run: sage -pip install -U https://github.com/3-manifolds/PLink/archive/master.zip
