name: sage-test

on: [push, pull_request]


jobs:
  test:
    name: Test on Sage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [9.1]

    container:
      image: sagemath/sagemath:${{ matrix.version }}

    steps:
      - name: Sage version
        run: sage --version

      - name: Make checkout work
        run: |
           sudo chown -R sage:sage /__w/SnapPy

      - name: Checkout
        uses: actions/checkout@v3

      - name: Go home
        # https://github.com/actions/runner/issues/863
        run: sudo chown sage:sage $HOME
        
      - name: Install PLink
        run:
          sage -pip install -U https://github.com/3-manifolds/PLink/archive/master.zip

      - name: Install LowIndex
        run:
          sage -pip install -U https://github.com/3-manifolds/low_index/archive/master.zip

      - name: Install snappy_manifolds
        run: sage -pip install -U https://github.com/3-manifolds/snappy_manifolds/archive/master.zip

      - name: Install spherogram
        run: sage -pip install -U https://github.com/3-manifolds/spherogram/archive/master.zip

      - name: Test spherogram
        run: sage -python -m spherogram.test

      - name: Install snappy
        run: |
          cd /__w/SnapPy/SnapPy
          sage -pip install wheel FXrays
          sage -python setup.py pip_install

      - name: Do the tests
        run: sage -python -m snappy.test
